# Generated by Django 5.1.3 on 2024-12-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_bank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank',
            new_name='BankCondition',
        ),
    ]
